version: "3.9"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: weatherapp_api
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
            - ./docker/php/php.ini:/usr/local/etc/php/conf.d/custom.ini
        environment:
            - PHP_OPCACHE_VALIDATE_TIMESTAMPS=1
        depends_on:
            - db

    nginx:
        image: nginx:alpine
        container_name: weatherapp_nginx
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - app

    db:
        image: postgres:16-alpine
        container_name: weatherapp_db
        restart: unless-stopped
        environment:
            POSTGRES_DB: weatherapp
            POSTGRES_USER: weatherapp
            POSTGRES_PASSWORD: weatherapp
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data

volumes:
    pgdata:
